#!/bin/bash
# Forwards 'git' invocations to the host, preserving certain important
# environment variables used by vim-fugitive.
extra_args=()

for var in GIT_EDITOR GIT_SEQUENCE_EDITOR GIT_ASKPASS
do
  if [[ "${!var}" ]]
  then
    extra_args+=( "--env=$var=${!var}" )
  fi
done

exec flatpak-spawn --host "${extra_args[@]}" "$(basename "$0")" "$@"
